# Project Name
TARGET = daisy_formant

USE_DAISYSP_LGPL = 1

# Sources
CPP_SOURCES = daisy_formant.cpp

# Library Locations
# Same relative paths as HW4 — both sit two levels below Music Tech/
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR  = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile